name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev clang

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          zig-version: 0.13.0

      - name: Build project
        run: zig build

      - name: Run tests
        run: zig build test
