name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm, windows-latest]

    env:
      TZ: "Pacific/Honolulu"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential libc6-dev clang

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build project
        run: zig build

      - name: Run tests
        run: zig build test --summary all

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: unixtime-${{ runner.os }}-${{ runner.arch }}
          path: |
            zig-out/bin/unixtime*
